export interface TripExpenseSplitterUI {
  [key: string]: unknown;
  tripNameLabel: string;
  tripNamePlaceholder: string;
  currencyLabel: string;
  travelersHeading: string;
  travelerPlaceholder: string;
  addTraveler: string;
  removeTraveler: string;
  expensesHeading: string;
  expenseDescriptionPlaceholder: string;
  amountLabel: string;
  payerLabel: string;
  participantsLabel: string;
  allTravelers: string;
  addExpense: string;
  emptyExpenses: string;
  resultHeading: string;
  totalSpent: string;
  transferCount: string;
  noTransfers: string;
  owes: string;
  receives: string;
  from: string;
  to: string;
  eachPays: string;
  eachReceives: string;
  settlementHint: string;
  copyLink: string;
  copied: string;
  exportJson: string;
  reset: string;
  removeExpense: string;
  deleteTrip: string;
  intro: string;
  statusBalanced: string;
  statusSettle: string;
  statusReady: string;
  currencyOptions: Array<{ code: string; symbol: string }>;
  defaultTripName: string;
  defaultTravelerNames: string[];
  defaultExpenseNames: string[];
}
