import type { ToolLocaleContent } from '../../../types';
import type { AirportConnectionBufferUI } from '../ui';
import { createAirportContent } from './shared';

const ui: AirportConnectionBufferUI = {
  flightDataHeading: 'フライト情報をすばやく入力', flightNumberLabel: '便名', flightNumberHint: '到着便: コードを入力するか搭乗券の最初の区間をスキャン', connectionFlightLabel: '乗り継ぎ便', connectionFlightHint: '任意: 次の便を別に入力', scanFileButton: '画像またはPDFをスキャン', scanCameraButton: 'カメラでスキャン', stopCameraButton: 'カメラを停止', scannerStatus: 'ローカルスキャナー: 画像を選ぶかカメラへのアクセスを許可してください。', airportLabel: '乗り継ぎ空港 (IATA)', arrivalAirportLabel: '到着空港', departureAirportLabel: '出発空港', terminalLabel: 'ターミナル', arrivalTerminalLabel: '到着ターミナル', departureTerminalLabel: '出発ターミナル', airportManualHint: '出典付きの移動時間がある場合はローカルカタログを使い、それ以外は経路を自分で確認してください。', arrivalLabel: '到着時刻', arrivalHint: '乗ってきた便の着陸予定時刻', departureLabel: '次の出発', departureHint: '乗り継ぎ便の出発時刻', baggageHeading: '手荷物と航空券', baggageHand: '機内持ち込みのみ', baggageChecked: '最終目的地まで預け入れ', baggageSelfTransfer: '別切り航空券 / セルフ乗り継ぎ', routeRuleHeading: '経路の条件', routeDomestic: '国内線から国内線', routeSchengen: 'シェンゲン外からシェンゲン内', routeUsInternational: '米国での国際線乗り継ぎ', routeCustom: 'カスタム', deplaningLabel: '到着便から降りる', deplaningHint: '降機、ボーディングブリッジ、出口', transferLabel: 'ターミナル移動', transferHint: '徒歩、バス、電車、ゲート移動', controlLabel: '保安検査またはパスポート審査', controlHint: '必要な検査をすべて含める', baggageLabel: '手荷物とチェックイン', baggageHint: '最終目的地まで預け入れる場合は0にしてください', personalBufferLabel: '自分用の余裕', personalBufferHint: '搭乗前に確保したい時間', gateCloseLabel: '出発前の搭乗口締切', gateCloseHint: '離陸時刻ではなくこの締切と比較', mctLabel: '比較するMCT', mctHint: '公式値を入力。0なら未入力', localDataLabel: '現地の移動データ', localDataKnown: '出典のある現地推定', localDataUnknown: '手動確認が必要', sourceLabel: '出典と制限', advancedSettingsLabel: '詳細設定', advancedSettingsHint: '移動、検査、手荷物、搭乗口、MCTの仮定を調整', delayHeading: '連鎖遅延シミュレーター', delayLabel: '遅延テスト', delayHint: '試したい到着遅延', delayZero: '+0分', delayFifteen: '+15分', delayThirty: '+30分', delayFortyFive: '+45分', presetsLabel: '経路タイプから開始', presetShort: '短い乗り継ぎ', presetStandard: '一般的な乗り継ぎ', presetLong: '長い乗り継ぎ', resultHeading: '乗り継ぎ余裕', windowLabel: 'フライト間の時間', plannedLabel: '予定する手順', gateWindowLabel: '搭乗口締切まで', mctLabelResult: 'MCT確認', mctUnknown: '公式MCTが未入力のため、出典付きの判定ではありません。', stressLabel: 'テスト遅延を加えた場合', marginLabel: '遅延時の余裕', statusComfortable: '余裕あり', statusTight: '余裕が少ない', statusMissed: '時間不足', timelineArrival: '着陸', timelineExit: '降機', timelineTransfer: '移動', timelineControl: '検査', timelineGate: '搭乗口締切', timelineDeparture: '出発', marginStatement: '予定した手順の後に{minutes}残ります。', stressStatement: 'テスト遅延を加えると{minutes}残ります。', invalidStatement: '有効で異なる到着時刻と出発時刻を入力してください。', mctStatement: '入力した時間を指定したMCTと比較しています。', sourceStatement: '移動時間は現地の推定です。検査、列、搭乗口変更、航空会社の締切で結果は変わります。', sampleButton: '一般的な乗り継ぎを読み込む', resetButton: 'リセット', minuteUnit: '分',
};

const content: ToolLocaleContent<AirportConnectionBufferUI> = createAirportContent({
  locale: 'ja', slug: 'airport-connection-buffer-calculator', title: '空港乗り継ぎ余裕時間計算機', description: '搭乗券のローカルスキャン、ターミナル移動、手荷物、搭乗口締切、経路条件、遅延テスト、MCT確認で空港乗り継ぎを見積もります。', ui,
  seo: [{ type: 'title', text: 'この計算機で分かること', level: 2 }, { type: 'paragraph', html: '乗り継ぎは時間枠であり、保証ではありません。到着から搭乗口締切までに必要な手順を差し引いて余裕を表示します。' }, { type: 'paragraph', html: 'ブラウザがPDF417またはAztecのローカル検出に対応していれば搭乗券画像をスキャンできます。空港とターミナルを手動で選ぶこともできます。' }, { type: 'title', text: '役立つ見積もりの作り方', level: 2 }, { type: 'list', items: ['予定到着時刻と次の出発時刻を入力する。', 'ターミナルや搭乗口までの実際の移動を加える。', '必要な検査、手荷物、チェックインを含める。', '搭乗口を探すための個人用の余裕を残す。', '遅延テストで余裕の減り方を確認する。'] }, { type: 'tip', title: '余裕があっても乗り継ぎは保証されません', html: '航空会社と空港の案内、検査、手荷物、搭乗締切を確認してください。リアルタイムの列や搭乗口変更は計算機では分かりません。' }],
  faq: [{ question: '公式の最低乗り継ぎ時間を知っていますか?', answer: '公式値を自分で入力した場合だけ比較できます。MCTは空港、ターミナル、航空会社、経路、航空券、検査で変わります。空欄は不明として表示されます。' }, { question: 'ターミナル移動には何を含めますか?', answer: '徒歩、電車、バス、シャトル、次の搭乗口までの移動を含めます。不明な場合は余裕を持って見積もり、空港案内を確認してください。' }, { question: '遅延テストは何のためですか?', answer: '到着遅延を仮定して、遅延なしと遅延ありの余裕を比較する機能です。遅延の確率を予測するものではありません。' }, { question: 'セルフ乗り継ぎでは何が変わりますか?', answer: '別切り航空券での手荷物受け取り、再チェックイン、追加移動を考慮して、より大きな時間を加えます。旅程の実際の手順を確認してください。' }],
  howTo: [{ name: 'フライト時間を入力', text: '到着時刻と次の便の出発時刻を入力します。時計上で早い出発は翌日として扱います。' }, { name: '手順を追加', text: 'ターミナル移動、検査、手荷物、チェックイン、搭乗前の個人用余裕を入力します。' }, { name: '遅延を試す', text: '到着遅延を選び、通常時と遅延時の余裕を比較します。' }, { name: '仮定を確認', text: 'ターミナル、検査、手荷物、搭乗締切、航空券条件の公式案内を確認します。' }], howToTitle: '乗り継ぎ余裕時間の見積もり方',
});

export { content };
