import type { ToolLocaleContent } from '../../../types';
import type { AirportConnectionBufferUI } from '../ui';
import { createAirportContent } from './shared';

const ui: AirportConnectionBufferUI = {
  flightDataHeading: '빠른 항공편 정보 입력', flightNumberLabel: '항공편 번호', flightNumberHint: '도착 항공편: 코드를 입력하거나 탑승권의 첫 구간을 스캔하세요', connectionFlightLabel: '연결 항공편', connectionFlightHint: '선택 사항: 다음 항공편을 따로 추가하세요', scanFileButton: '이미지 또는 PDF 스캔', scanCameraButton: '카메라로 스캔', stopCameraButton: '카메라 중지', scannerStatus: '로컬 스캐너: 이미지를 선택하거나 카메라 접근을 허용하세요.', airportLabel: '환승 공항 (IATA)', arrivalAirportLabel: '도착 공항', departureAirportLabel: '출발 공항', terminalLabel: '터미널', arrivalTerminalLabel: '도착 터미널', departureTerminalLabel: '출발 터미널', airportManualHint: '출처가 있는 이동 시간이 있으면 로컬 목록을 사용하고, 없으면 경로를 직접 확인하세요.', arrivalLabel: '도착 시간', arrivalHint: '도착 항공편이 착륙 예정인 시간', departureLabel: '다음 출발', departureHint: '연결 항공편이 출발하는 시간', baggageHeading: '수하물과 항공권 유형', baggageHand: '기내 수하물만', baggageChecked: '최종 목적지까지 위탁', baggageSelfTransfer: '별도 항공권 / 셀프 환승', routeRuleHeading: '경로 규칙', routeDomestic: '국내선에서 국내선', routeSchengen: '비셴겐에서 셴겐', routeUsInternational: '미국 내 국제선 환승', routeCustom: '직접 설정', deplaningLabel: '도착 항공기에서 내리기', deplaningHint: '하차, 탑승교, 출구', transferLabel: '터미널 이동', transferHint: '도보, 버스, 열차 또는 게이트 이동', controlLabel: '보안 또는 여권 심사', controlHint: '필요한 모든 검사를 포함하세요', baggageLabel: '수하물과 체크인', baggageHint: '수하물이 최종 목적지까지 연결되면 0을 사용하세요', personalBufferLabel: '개인 여유 시간', personalBufferHint: '탑승 전에 확보하고 싶은 시간', gateCloseLabel: '출발 전 게이트 마감', gateCloseHint: '이 마감 시간과 비교하세요. 이륙 시간과 비교하지 않습니다', mctLabel: '비교할 MCT', mctHint: '공식 값을 입력하세요. 0은 미입력으로 둡니다', localDataLabel: '현지 이동 데이터', localDataKnown: '출처가 있는 현지 추정', localDataUnknown: '수동 확인 필요', sourceLabel: '출처와 한계', advancedSettingsLabel: '고급 설정', advancedSettingsHint: '이동, 검사, 수하물, 게이트, MCT 가정을 조정하세요', delayHeading: '연쇄 지연 시뮬레이터', delayLabel: '지연 테스트', delayHint: '시험할 추가 도착 지연', delayZero: '+0분', delayFifteen: '+15분', delayThirty: '+30분', delayFortyFive: '+45분', presetsLabel: '경로 유형으로 시작', presetShort: '짧은 환승', presetStandard: '일반적인 환승', presetLong: '긴 환승', resultHeading: '환승 여유', windowLabel: '항공편 사이 시간', plannedLabel: '예상 단계', gateWindowLabel: '게이트 마감까지', mctLabelResult: 'MCT 확인', mctUnknown: '공식 MCT를 입력하지 않았으므로 출처가 있는 판정이 아닙니다.', stressLabel: '시험 지연 적용', marginLabel: '지연 시 여유', statusComfortable: '여유 있음', statusTight: '여유가 적음', statusMissed: '시간 부족', timelineArrival: '착륙', timelineExit: '항공기에서 내리기', timelineTransfer: '이동', timelineControl: '검사', timelineGate: '게이트 마감', timelineDeparture: '출발', marginStatement: '예상 단계 후 {minutes} 남습니다.', stressStatement: '시험 지연을 더하면 {minutes} 남습니다.', invalidStatement: '유효하고 서로 다른 도착 및 출발 시간을 입력하세요.', mctStatement: '입력한 시간을 지정한 MCT와 비교합니다.', sourceStatement: '이동 시간은 현지 추정치입니다. 검사, 대기열, 게이트 변경, 항공사 마감 시간에 따라 결과가 달라질 수 있습니다.', sampleButton: '일반적인 환승 불러오기', resetButton: '초기화', minuteUnit: '분',
};

const content: ToolLocaleContent<AirportConnectionBufferUI> = createAirportContent({
  locale: 'ko', slug: 'airport-connection-buffer-calculator', title: '공항 환승 여유 시간 계산기', description: '탑승권 로컬 스캔, 터미널 이동, 수하물 유형, 게이트 마감, 경로 규칙, 지연 테스트와 MCT 확인으로 공항 환승을 계산합니다.', ui,
  seo: [{ type: 'title', text: '이 계산기가 측정하는 것', level: 2 }, { type: 'paragraph', html: '환승은 시간 창일 뿐 보장이 아닙니다. 도착부터 게이트 마감까지 필요한 단계를 빼고 남은 여유를 보여줍니다.' }, { type: 'paragraph', html: '브라우저가 PDF417 또는 Aztec 로컬 감지를 지원하면 탑승권 이미지를 스캔할 수 있으며, 공항과 터미널을 직접 선택할 수도 있습니다.' }, { type: 'title', text: '유용한 추정값 만들기', level: 2 }, { type: 'list', items: ['예정 도착과 다음 출발 시간을 입력합니다.', '터미널이나 게이트 사이의 실제 이동을 더합니다.', '필요한 검사, 수하물, 체크인을 포함합니다.', '게이트를 찾고 탑승할 개인 여유를 남깁니다.', '지연 테스트로 여유가 얼마나 줄어드는지 확인합니다.'] }, { type: 'tip', title: '긍정적인 여유가 환승을 보장하지는 않습니다', html: '항공사와 공항 안내, 검사, 수하물 규정, 탑승 마감 시간을 확인하세요. 실시간 대기열과 게이트 변경은 계산기가 알 수 없습니다.' }],
  faq: [{ question: '공식 최소 환승 시간을 알고 있나요?', answer: '공식 값을 직접 입력한 경우에만 비교합니다. MCT는 공항, 터미널, 항공사, 경로, 항공권, 검사에 따라 달라집니다. 빈 칸은 알 수 없음으로 표시됩니다.' }, { question: '터미널 이동에 무엇을 넣어야 하나요?', answer: '도보, 열차, 버스, 셔틀과 다음 게이트까지의 이동을 포함하세요. 모르면 여유 있게 추정하고 공항 안내를 확인하세요.' }, { question: '지연 테스트는 무엇인가요?', answer: '도착 지연을 가정해 지연 전후의 남은 여유를 비교하는 기능입니다. 지연 확률을 예측하지는 않습니다.' }, { question: '셀프 환승 모드는 무엇을 바꾸나요?', answer: '별도 항공권에서 수하물 찾기, 재체크인, 추가 이동을 위해 더 큰 시간을 더합니다. 실제 여정의 절차를 확인하세요.' }],
  howTo: [{ name: '항공편 시간 입력', text: '도착 시간과 다음 항공편의 출발 시간을 입력합니다. 시계상 더 이른 출발은 다음 날로 처리됩니다.' }, { name: '환승 단계 추가', text: '터미널 이동, 검사, 수하물, 체크인과 탑승 전 개인 여유를 입력합니다.' }, { name: '지연 테스트', text: '도착 지연을 선택하고 일반 여유와 지연 시 여유를 비교합니다.' }, { name: '가정 확인', text: '터미널, 검사, 수하물, 탑승 마감, 항공권 조건에 대한 공식 정보를 확인합니다.' }], howToTitle: '항공편 환승 여유 시간 계산 방법',
});

export { content };
