import type { ToolLocaleContent } from '../../../types';
import type { AirportConnectionBufferUI } from '../ui';
import { createAirportContent } from './shared';

const ui: AirportConnectionBufferUI = {
  flightDataHeading: '快速输入航班信息', flightNumberLabel: '航班号', flightNumberHint: '到达航班: 输入代码，或扫描登机牌的第一段行程', connectionFlightLabel: '联程航班', connectionFlightHint: '可选: 单独添加下一段航班', scanFileButton: '扫描图片或PDF', scanCameraButton: '使用相机扫描', stopCameraButton: '停止相机', scannerStatus: '本地扫描器: 选择图片或允许相机访问。', airportLabel: '中转机场 (IATA)', arrivalAirportLabel: '到达机场', departureAirportLabel: '出发机场', terminalLabel: '航站楼', arrivalTerminalLabel: '到达航站楼', departureTerminalLabel: '出发航站楼', airportManualHint: '有来源的中转时间可使用本地目录，否则请自行核对路线。', arrivalLabel: '到达时间', arrivalHint: '进港航班预计落地的时间', departureLabel: '下一次出发', departureHint: '联程航班起飞的时间', baggageHeading: '行李和机票类型', baggageHand: '仅手提行李', baggageChecked: '行李直挂目的地', baggageSelfTransfer: '分开购票 / 自助转机', routeRuleHeading: '路线规则', routeDomestic: '国内转国内', routeSchengen: '非申根转申根', routeUsInternational: '美国境内国际转机', routeCustom: '自定义', deplaningLabel: '离开到达航班', deplaningHint: '下机、廊桥和出口', transferLabel: '航站楼转移', transferHint: '步行、巴士、火车或登机口转移', controlLabel: '安检或护照检查', controlHint: '加入所有必需的检查', baggageLabel: '行李和办理值机', baggageHint: '行李直挂时请输入0', personalBufferLabel: '个人缓冲时间', personalBufferHint: '希望在登机前保留的时间', gateCloseLabel: '起飞前登机口关闭', gateCloseHint: '与此截止时间比较，不要与起飞时间比较', mctLabel: '用于比较的MCT', mctHint: '输入官方数值，输入0则保持未知', localDataLabel: '本地转移数据', localDataKnown: '有来源的本地估计', localDataUnknown: '需要手动核对', sourceLabel: '来源和限制', advancedSettingsLabel: '高级设置', advancedSettingsHint: '调整步行、检查、行李、登机口和MCT假设', delayHeading: '连续延误模拟器', delayLabel: '延误测试', delayHint: '要测试的额外到达延误', delayZero: '+0分钟', delayFifteen: '+15分钟', delayThirty: '+30分钟', delayFortyFive: '+45分钟', presetsLabel: '从路线类型开始', presetShort: '短途转机', presetStandard: '典型转机', presetLong: '长途转机', resultHeading: '转机余量', windowLabel: '航班间隔时间', plannedLabel: '计划步骤', gateWindowLabel: '到登机口关闭', mctLabelResult: 'MCT检查', mctUnknown: '未输入官方MCT，这不是有来源的通过或不通过结论。', stressLabel: '加入测试延误', marginLabel: '延误后的余量', statusComfortable: '余量充足', statusTight: '余量紧张', statusMissed: '时间不足', timelineArrival: '落地', timelineExit: '离开飞机', timelineTransfer: '移动', timelineControl: '检查', timelineGate: '登机口截止', timelineDeparture: '出发', marginStatement: '完成计划步骤后还剩{minutes}。', stressStatement: '加入测试延误后还剩{minutes}。', invalidStatement: '请输入有效且不同的到达和出发时间，以查看转机时间窗口。', mctStatement: '输入的时间窗口会与指定的MCT比较。', sourceStatement: '转移时间是本地估计值，检查、排队、登机口变化和航空公司截止时间都可能改变结果。', sampleButton: '加载典型转机', resetButton: '重置', minuteUnit: '分钟',
};

const content: ToolLocaleContent<AirportConnectionBufferUI> = createAirportContent({
  locale: 'zh', slug: 'airport-connection-buffer-calculator', title: '机场转机余量计算器', description: '通过本地扫描登机牌、航站楼转移、行李类型、登机口关闭时间、路线检查、延误测试和MCT核对来估算机场转机。', ui,
  seo: [{ type: 'title', text: '这个计算器测量什么', level: 2 }, { type: 'paragraph', html: '转机只有时间窗口，不代表保证。计算器从到达时间到登机口关闭之间扣除预计步骤，显示剩余余量。' }, { type: 'paragraph', html: '如果浏览器支持PDF417或Aztec本地检测，可以扫描登机牌图片，也可以手动选择IATA机场和航站楼。' }, { type: 'title', text: '如何建立有用的估算', level: 2 }, { type: 'list', items: ['输入计划到达和下一次出发时间。', '加入航站楼或登机口之间的实际移动。', '包含适用的检查、行李和办理值机步骤。', '为寻找登机口和登机保留个人余量。', '用延误测试查看余量如何快速消失。'] }, { type: 'tip', title: '有余量不等于保证转机成功', html: '请核对航空公司和机场说明、检查要求、行李规则及登机截止时间。实时排队和登机口变化不在计算器掌握范围内。' }],
  faq: [{ question: '计算器知道官方最短转机时间吗?', answer: '只有你自己输入官方数值后才能比较。MCT取决于机场、航站楼、航空公司、路线、机票和检查要求。空白数值会显示为未知。' }, { question: '航站楼转移应该包括什么?', answer: '包括步行、火车、巴士、接驳车以及前往下一个登机口的移动。如果不清楚，请保守估算并查看机场说明。' }, { question: '延误测试有什么用?', answer: '它是透明的假设场景: 添加到达延误，比较有无延误时的剩余余量。它不会预测延误概率。' }, { question: '自助转机模式会改变什么?', answer: '它会为分开购票时取行李、重新值机和额外移动增加更宽裕的时间。仍需核对行程的实际步骤。' }],
  howTo: [{ name: '输入航班时间窗口', text: '填写到达时间和下一航班的出发时间。时钟上更早的出发时间会被视为第二天。' }, { name: '添加转机步骤', text: '填写航站楼移动、检查、行李、值机和登机前的个人余量。' }, { name: '测试延误', text: '选择到达延误，比较正常余量和延误后的余量。' }, { name: '核对假设', text: '查看航站楼、检查、行李、登机截止和机票条件的官方信息。' }], howToTitle: '如何估算航班转机余量',
});

export { content };
